apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default1.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            return 200 "server1";
            add_header  Content-Type text/plain;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
  default2.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            return 200 "server2";
            add_header  Content-Type text/plain;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }